[package]
name = "dice-roll"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]
edition = "2018"

[dependencies]
pom = "3.1.0"
rand = "0.7.3"
rocket = "0.4.4"
rocket_contrib = "0.4.4"
serde = { version="1.0.110", features = ["derive"] }
