[package]
name = "dice-roll"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]
edition = "2021"

[dependencies]
pom = "3.2.0"
rand = "0.8.5"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
serde = { version = "1.0.160", features = ["derive"] }
